# Data from Open Trivia DB


question_data = {"response_code": 0,
                 "results": [
                     {"category": "Geography",
                      "type": "boolean",
                      "difficulty": "easy",
                      "question": "Greenland is almost as big as Africa.",
                      "correct_answer": "False",
                      "incorrect_answers": ["True"]},
                     {"category": "Geography", "type": "boolean", "difficulty": "easy",
                      "question": "A group of islands is called an 'archipelago'.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"category": "Geography", "type": "boolean", "difficulty": "easy",
                      "question": "The Republic of Malta is the smallest microstate worldwide.",
                      "correct_answer": "False", "incorrect_answers": ["True"]},
                     {"category": "Geography", "type": "boolean", "difficulty": "easy",
                      "question": "Vatican City is a country.", "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"category": "Geography", "type": "boolean", "difficulty": "easy",
                      "question": "San Marino is the only country completely surrounded by another country.",
                      "correct_answer": "False", "incorrect_answers": ["True"]},
                     {"category": "Geography", "type": "boolean", "difficulty": "easy",
                      "question": "California is larger than Japan.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"category": "Geography", "type": "boolean", "difficulty": "easy",
                      "question": "Hungary is the only country in the world beginning with H.",
                      "correct_answer": "False", "incorrect_answers": ["True"]},
                     {"category": "Geography", "type": "boolean", "difficulty": "easy",
                      "question": "New Haven is the capital city of the state of Connecticut in the United States.",
                      "correct_answer": "False", "incorrect_answers": ["True"]},
                     {"category": "Geography", "type": "boolean", "difficulty": "easy",
                      "question": "Nova Scotia is on the east coast of Canada.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"category": "Geography", "type": "boolean",
                      "difficulty": "easy",
                      "question": "Rhode Island is actually located on the US mainland,"
                                  " despite its name.",
                      "correct_answer": "True",
                      "incorrect_answers": ["False"]}]}
